// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Retailio.Data;

#nullable disable

namespace Retailio.backend.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260615125834_create_roles_has_permissions_table")]
    partial class create_roles_has_permissions_table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Retailio.Models.Business", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("business_name")
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("business_name");

                    b.Property<string>("business_type")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("business_type");

                    b.Property<int>("user_id")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("id");

                    b.HasIndex("user_id");

                    b.ToTable("businesses", (string)null);
                });

            modelBuilder.Entity("Retailio.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Names")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("names");

                    b.Property<string>("Slugs")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("slugs");

                    b.HasKey("Id");

                    b.ToTable("permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Names = "Dashboard",
                            Slugs = "dashboard"
                        },
                        new
                        {
                            Id = 2,
                            Names = "Customers",
                            Slugs = "customers"
                        },
                        new
                        {
                            Id = 3,
                            Names = "Products",
                            Slugs = "products"
                        },
                        new
                        {
                            Id = 4,
                            Names = "Sales",
                            Slugs = "sales"
                        },
                        new
                        {
                            Id = 5,
                            Names = "Settings",
                            Slugs = "settings"
                        },
                        new
                        {
                            Id = 6,
                            Names = "Inventory",
                            Slugs = "inventory"
                        },
                        new
                        {
                            Id = 7,
                            Names = "Employees",
                            Slugs = "employees"
                        },
                        new
                        {
                            Id = 8,
                            Names = "Reports",
                            Slugs = "reports"
                        },
                        new
                        {
                            Id = 9,
                            Names = "Recovery",
                            Slugs = "recovery"
                        });
                });

            modelBuilder.Entity("Retailio.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("role_title");

                    b.Property<int>("business_id")
                        .HasColumnType("int")
                        .HasColumnName("business_id");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.HasKey("Id");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("Retailio.Models.RolesHasPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PermissionId")
                        .HasColumnType("int")
                        .HasColumnName("permission_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("roles_has_permissions");
                });

            modelBuilder.Entity("Retailio.Models.users", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password");

                    b.Property<int>("business_id")
                        .HasColumnType("int")
                        .HasColumnName("business_id");

                    b.Property<int?>("status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("username")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("username");

                    b.HasKey("id");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            id = 1,
                            email = "superadmin@gmail.com",
                            password = "186cf774c97b60a1c106ef718d10970a6a06e06bef89553d9ae65d938a886eae",
                            business_id = 0,
                            status = 1,
                            username = "superadmin"
                        });
                });

            modelBuilder.Entity("Retailio.Models.Business", b =>
                {
                    b.HasOne("Retailio.Models.users", "User")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Retailio.Models.RolesHasPermission", b =>
                {
                    b.HasOne("Retailio.Models.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Retailio.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
