// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Retailio.Data;

#nullable disable

namespace Retailio.backend.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260615131949_create_recoveries_table")]
    partial class create_recoveries_table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Retailio.Models.Brand", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("brand_title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("brand_title");

                    b.HasKey("id");

                    b.ToTable("brands");
                });

            modelBuilder.Entity("Retailio.Models.Business", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("business_name")
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("business_name");

                    b.Property<string>("business_type")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("business_type");

                    b.Property<int>("user_id")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("id");

                    b.HasIndex("user_id");

                    b.ToTable("businesses", (string)null);
                });

            modelBuilder.Entity("Retailio.Models.Category", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("category_title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("category_title");

                    b.HasKey("id");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("Retailio.Models.Credit", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("customer_id")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<string>("date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("date");

                    b.Property<string>("file")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("file");

                    b.Property<decimal>("paid")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("paid");

                    b.Property<int?>("payment_method")
                        .HasColumnType("int")
                        .HasColumnName("payment_method");

                    b.Property<decimal>("remaining")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("remaining");

                    b.Property<int?>("status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<decimal>("total_credit")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_credit");

                    b.HasKey("id");

                    b.HasIndex("customer_id");

                    b.ToTable("credits");
                });

            modelBuilder.Entity("Retailio.Models.CreditDetail", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<int>("credit_id")
                        .HasColumnType("int")
                        .HasColumnName("credit_id");

                    b.Property<string>("date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("date");

                    b.Property<string>("file")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("file");

                    b.Property<int?>("payment_method")
                        .HasColumnType("int")
                        .HasColumnName("payment_method");

                    b.Property<int>("sale_id")
                        .HasColumnType("int")
                        .HasColumnName("sale_id");

                    b.Property<int?>("status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("id");

                    b.HasIndex("credit_id");

                    b.ToTable("credits_details");
                });

            modelBuilder.Entity("Retailio.Models.Currency", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("code")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("code");

                    b.Property<decimal>("exchange_rate")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("exchange_rate");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<string>("symbol")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("symbol");

                    b.HasKey("id");

                    b.ToTable("currencies");
                });

            modelBuilder.Entity("Retailio.Models.Employee", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<string>("cnic")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cnic");

                    b.Property<string>("date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("date");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("full_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("full_name");

                    b.Property<string>("image_path")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_path");

                    b.Property<string>("mobile_no")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mobile_no");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password");

                    b.Property<int?>("role_id")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<decimal>("salary")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("salary");

                    b.Property<int?>("status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("id");

                    b.ToTable("employee");
                });

            modelBuilder.Entity("Retailio.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Names")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("names");

                    b.Property<string>("Slugs")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("slugs");

                    b.HasKey("Id");

                    b.ToTable("permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Names = "Dashboard",
                            Slugs = "dashboard"
                        },
                        new
                        {
                            Id = 2,
                            Names = "Customers",
                            Slugs = "customers"
                        },
                        new
                        {
                            Id = 3,
                            Names = "Products",
                            Slugs = "products"
                        },
                        new
                        {
                            Id = 4,
                            Names = "Sales",
                            Slugs = "sales"
                        },
                        new
                        {
                            Id = 5,
                            Names = "Settings",
                            Slugs = "settings"
                        },
                        new
                        {
                            Id = 6,
                            Names = "Inventory",
                            Slugs = "inventory"
                        },
                        new
                        {
                            Id = 7,
                            Names = "Employees",
                            Slugs = "employees"
                        },
                        new
                        {
                            Id = 8,
                            Names = "Reports",
                            Slugs = "reports"
                        },
                        new
                        {
                            Id = 9,
                            Names = "Recovery",
                            Slugs = "recovery"
                        });
                });

            modelBuilder.Entity("Retailio.Models.ProductService", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("barcode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("barcode");

                    b.Property<int?>("brand_id")
                        .HasColumnType("int")
                        .HasColumnName("brand_id");

                    b.Property<int?>("category_id")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<string>("expiry_date")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("expiry_date");

                    b.Property<string>("item_type")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("item_type");

                    b.Property<string>("manufacture_date")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("manufacture_date");

                    b.Property<string>("pic")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("pic");

                    b.Property<string>("prod_name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("prod_name");

                    b.Property<string>("prod_state")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("prod_state");

                    b.Property<string>("remarks")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("remarks");

                    b.Property<int?>("size")
                        .HasColumnType("int")
                        .HasColumnName("size");

                    b.Property<int?>("status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("unit")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("unit");

                    b.HasKey("id");

                    b.ToTable("products_services");
                });

            modelBuilder.Entity("Retailio.Models.Recovery", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("credit_id")
                        .HasColumnType("int")
                        .HasColumnName("credit_id");

                    b.Property<int>("customer_id")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<string>("date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("date");

                    b.Property<string>("file")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("file");

                    b.Property<decimal>("paid")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("paid");

                    b.Property<decimal>("remaining")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("remaining");

                    b.Property<int?>("status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<decimal>("total_credit")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_credit");

                    b.HasKey("id");

                    b.ToTable("recoveries");
                });

            modelBuilder.Entity("Retailio.Models.ReturnDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("date");

                    b.Property<string>("inv_no")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("inv_no")
                        .HasColumnOrder(1);

                    b.Property<int>("item_id")
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    b.Property<int?>("payment_method")
                        .HasColumnType("int")
                        .HasColumnName("payment_method");

                    b.Property<int>("qty")
                        .HasColumnType("int")
                        .HasColumnName("qty");

                    b.Property<int?>("sale_id")
                        .HasColumnType("int")
                        .HasColumnName("sale_id");

                    b.Property<int?>("status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<decimal>("total_price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_price");

                    b.Property<decimal>("unit_price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.ToTable("return_details", (string)null);
                });

            modelBuilder.Entity("Retailio.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("role_title");

                    b.Property<int>("business_id")
                        .HasColumnType("int")
                        .HasColumnName("business_id");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.HasKey("Id");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("Retailio.Models.RolesHasPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PermissionId")
                        .HasColumnType("int")
                        .HasColumnName("permission_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("roles_has_permissions");
                });

            modelBuilder.Entity("Retailio.Models.Sale", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("item_id")
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    b.Property<int>("qty")
                        .HasColumnType("int")
                        .HasColumnName("qty");

                    b.Property<int>("sale_id")
                        .HasColumnType("int")
                        .HasColumnName("sale_id");

                    b.Property<int?>("status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<decimal>("total_price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_price");

                    b.Property<decimal>("unit_price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("id");

                    b.HasIndex("sale_id");

                    b.ToTable("sale_details", (string)null);
                });

            modelBuilder.Entity("Retailio.Models.SaleHeader", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("customer_id")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<string>("date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("date");

                    b.Property<decimal>("discount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("discount");

                    b.Property<decimal>("due")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("due");

                    b.Property<decimal>("gross_total")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("gross_total");

                    b.Property<string>("inv_no")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("inv_no")
                        .HasColumnOrder(1);

                    b.Property<decimal>("net_payable")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("net_payable");

                    b.Property<decimal>("paid")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("paid");

                    b.Property<int?>("payment_method")
                        .HasColumnType("int")
                        .HasColumnName("payment_method");

                    b.Property<int?>("status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("id");

                    b.ToTable("sales", (string)null);
                });

            modelBuilder.Entity("Retailio.Models.StockDetail", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("date_of_expiry")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("date_of_expiry");

                    b.Property<string>("date_of_manafacture")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("date_of_manafacture");

                    b.Property<string>("item_barcode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("item_barcode");

                    b.Property<decimal>("pur_price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("pur_price");

                    b.Property<int>("quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<decimal>("sale_price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("sale_price");

                    b.Property<int>("stock_alert")
                        .HasColumnType("int")
                        .HasColumnName("stock_alert");

                    b.Property<decimal>("total_pur_price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_pur_price");

                    b.Property<decimal>("whole_sale_price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("whole_sale_price");

                    b.HasKey("id");

                    b.ToTable("stock_details");
                });

            modelBuilder.Entity("Retailio.Models.StoreConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("address");

                    b.Property<string>("Branch")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("branch");

                    b.Property<string>("BusinessNature")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("business_nature");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("city");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comments");

                    b.Property<string>("LogoPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("logo_path");

                    b.Property<string>("OwnerName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("owner_name");

                    b.Property<string>("Phone1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("phone_1");

                    b.Property<string>("Phone2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("phone_2");

                    b.Property<string>("ShopName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("shop_name");

                    b.Property<string>("ShopNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("shop_no");

                    b.HasKey("Id");

                    b.ToTable("store_configurations");
                });

            modelBuilder.Entity("Retailio.Models.Subscription", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("business_id")
                        .HasColumnType("int")
                        .HasColumnName("business_id");

                    b.Property<string>("expires_at")
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("expires_at");

                    b.Property<string>("plan")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("plan");

                    b.Property<string>("started_at")
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("started_at");

                    b.Property<int?>("status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("id");

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("Retailio.Models.UserHasRoles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RolesHasPermissionId")
                        .HasColumnType("int")
                        .HasColumnName("roles_has_permission_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("RolesHasPermissionId");

                    b.HasIndex("UserId");

                    b.ToTable("user_has_roles");
                });

            modelBuilder.Entity("Retailio.Models.customers", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<string>("cnic")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cnic");

                    b.Property<string>("contact")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contact");

                    b.Property<decimal?>("credit_limit")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("credit_limit");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int?>("status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("id");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("Retailio.Models.stock_history", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("date")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("date");

                    b.Property<decimal>("new_purchase_price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("new_purchase_price");

                    b.Property<int>("new_quantity")
                        .HasColumnType("int")
                        .HasColumnName("new_quantity");

                    b.Property<decimal>("new_sale_price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("new_sale_price");

                    b.Property<decimal>("old_purchase_price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("old_purchase_price");

                    b.Property<int>("old_quantity")
                        .HasColumnType("int")
                        .HasColumnName("old_quantity");

                    b.Property<decimal>("old_sale_price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("old_sale_price");

                    b.Property<int>("product_id")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<string>("remarks")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("remarks");

                    b.HasKey("id");

                    b.ToTable("stock_history");
                });

            modelBuilder.Entity("Retailio.Models.users", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password");

                    b.Property<int>("business_id")
                        .HasColumnType("int")
                        .HasColumnName("business_id");

                    b.Property<int?>("status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("username")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("username");

                    b.HasKey("id");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            id = 1,
                            email = "superadmin@gmail.com",
                            password = "186cf774c97b60a1c106ef718d10970a6a06e06bef89553d9ae65d938a886eae",
                            business_id = 0,
                            status = 1,
                            username = "superadmin"
                        });
                });

            modelBuilder.Entity("Retailio.Models.Brand", b =>
                {
                    b.HasOne("Retailio.Models.Business", "Business")
                        .WithMany()
                        .HasForeignKey("business_id");

                    b.Navigation("Business");
                });

            modelBuilder.Entity("Retailio.Models.Business", b =>
                {
                    b.HasOne("Retailio.Models.users", "User")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Retailio.Models.Category", b =>
                {
                    b.HasOne("Retailio.Models.Business", "Business")
                        .WithMany()
                        .HasForeignKey("business_id");

                    b.Navigation("Business");
                });

            modelBuilder.Entity("Retailio.Models.Credit", b =>
                {
                    b.HasOne("Retailio.Models.Business", "Business")
                        .WithMany()
                        .HasForeignKey("business_id");

                    b.HasOne("Retailio.Models.customers", null)
                        .WithMany()
                        .HasForeignKey("customer_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("Retailio.Models.CreditDetail", b =>
                {
                    b.HasOne("Retailio.Models.Business", "Business")
                        .WithMany()
                        .HasForeignKey("business_id");

                    b.HasOne("Retailio.Models.Credit", null)
                        .WithMany()
                        .HasForeignKey("credit_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("Retailio.Models.Currency", b =>
                {
                    b.HasOne("Retailio.Models.Business", "Business")
                        .WithMany()
                        .HasForeignKey("business_id");

                    b.Navigation("Business");
                });

            modelBuilder.Entity("Retailio.Models.ProductService", b =>
                {
                    b.HasOne("Retailio.Models.Business", "Business")
                        .WithMany()
                        .HasForeignKey("business_id");

                    b.Navigation("Business");
                });

            modelBuilder.Entity("Retailio.Models.Recovery", b =>
                {
                    b.HasOne("Retailio.Models.Business", "Business")
                        .WithMany()
                        .HasForeignKey("business_id");

                    b.Navigation("Business");
                });

            modelBuilder.Entity("Retailio.Models.ReturnDetail", b =>
                {
                    b.HasOne("Retailio.Models.Business", "Business")
                        .WithMany()
                        .HasForeignKey("business_id");

                    b.Navigation("Business");
                });

            modelBuilder.Entity("Retailio.Models.RolesHasPermission", b =>
                {
                    b.HasOne("Retailio.Models.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Retailio.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Retailio.Models.Sale", b =>
                {
                    b.HasOne("Retailio.Models.Business", "Business")
                        .WithMany()
                        .HasForeignKey("business_id");

                    b.HasOne("Retailio.Models.SaleHeader", "SaleHeader")
                        .WithMany("SaleDetails")
                        .HasForeignKey("sale_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SaleHeader");

                    b.Navigation("Business");
                });

            modelBuilder.Entity("Retailio.Models.SaleHeader", b =>
                {
                    b.HasOne("Retailio.Models.Business", "Business")
                        .WithMany()
                        .HasForeignKey("business_id");

                    b.Navigation("Business");
                });

            modelBuilder.Entity("Retailio.Models.StockDetail", b =>
                {
                    b.HasOne("Retailio.Models.Business", "Business")
                        .WithMany()
                        .HasForeignKey("business_id");

                    b.Navigation("Business");
                });

            modelBuilder.Entity("Retailio.Models.StoreConfiguration", b =>
                {
                    b.HasOne("Retailio.Models.Business", "Business")
                        .WithMany()
                        .HasForeignKey("business_id");

                    b.Navigation("Business");
                });

            modelBuilder.Entity("Retailio.Models.Subscription", b =>
                {
                    b.HasOne("Retailio.Models.Business", "Business")
                        .WithMany()
                        .HasForeignKey("business_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");
                });

            

            modelBuilder.Entity("Retailio.Models.customers", b =>
                {
                    b.HasOne("Retailio.Models.Business", "Business")
                        .WithMany()
                        .HasForeignKey("business_id");

                    b.Navigation("Business");
                });

            modelBuilder.Entity("Retailio.Models.SaleHeader", b =>
                {
                    b.Navigation("SaleDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
