// <auto-generated />
using E_Invoice_system.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E_Invoice_system.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260521114900_create_credits_table")]
    partial class create_credits_table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("E_Invoice_system.Models.Brand", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("brand_title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("brand_title");

                    b.HasKey("id");

                    b.ToTable("brands");
                });

            modelBuilder.Entity("E_Invoice_system.Models.Category", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("category_title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("category_title");

                    b.HasKey("id");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("E_Invoice_system.Models.Credit", b =>
            {
                b.Property<int>("id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasColumnName("id");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                b.Property<string>("inv_no")
                    .HasColumnType("nvarchar(max)")
                    .HasColumnName("inv_no");

                b.Property<int>("customer_id")
                    .HasColumnType("int")
                    .HasColumnName("customer_id");

                b.Property<string>("date")
                    .HasColumnType("nvarchar(max)")
                    .HasColumnName("date");

                b.Property<decimal>("discount")
                    .HasColumnType("decimal(18,2)")
                    .HasColumnName("discount");

                b.Property<decimal>("grand_total")
                    .HasColumnType("decimal(18,2)")
                    .HasColumnName("grand_total");

                b.Property<decimal>("paid_amount")
                    .HasColumnType("decimal(18,2)")
                    .HasColumnName("paid_amount");

                b.Property<decimal>("remaining_amount")
                    .HasColumnType("decimal(18,2)")
                    .HasColumnName("remaining_amount");

                b.HasKey("id");

                b.ToTable("credits");
            });

            modelBuilder.Entity("E_Invoice_system.Models.Currency", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("code")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("code");

                    b.Property<decimal>("exchange_rate")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("exchange_rate");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<string>("symbol")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("symbol");

                    b.HasKey("id");

                    b.ToTable("currencies");
                });

            modelBuilder.Entity("E_Invoice_system.Models.Employee", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<string>("cnic")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cnic");

                    b.Property<string>("date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("date");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("emp_code")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("emp_code");

                    b.Property<string>("full_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("full_name");

                    b.Property<string>("image_path")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_path");

                    b.Property<string>("mobile_no")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mobile_no");

                    b.Property<decimal>("salary")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("salary");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.HasKey("id");

                    b.ToTable("employee");

                    b.HasData(
                        new
                        {
                            id = 1,
                            address = "Admin Address",
                            cnic = "00000-0000000-0",
                            date = "1-1-2024",
                            email = "admin@pos.com",
                            emp_code = "EMP-001",
                            full_name = "Admin",
                            mobile_no = "0000-0000000",
                            salary = 0m,
                            status = "Active"
                        });
                });

            modelBuilder.Entity("E_Invoice_system.Models.ProductService", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("barcode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("barcode");

                    b.Property<int?>("brand_id")
                        .HasColumnType("int")
                        .HasColumnName("brand_id");

                    b.Property<int?>("category_id")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<string>("expiry_date")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("expiry_date");

                    b.Property<string>("item_type")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("item_type");

                    b.Property<string>("manufacture_date")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("manufacture_date");

                    b.Property<string>("pic")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("pic");

                    b.Property<string>("prod_name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("prod_name");

                    b.Property<string>("prod_state")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("prod_state");

                    b.Property<string>("remarks")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("remarks");

                    b.Property<int?>("size")
                        .HasColumnType("int")
                        .HasColumnName("size");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<string>("unit")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("unit");

                    b.HasKey("id");

                    b.ToTable("products_services");
                });

            modelBuilder.Entity("E_Invoice_system.Models.ReturnDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Method")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("method");

                    b.Property<int>("SaleId")
                        .HasColumnType("int")
                        .HasColumnName("sale_id");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<string>("inv_no")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("inv_no")
                        .HasColumnOrder(1);

                    b.Property<string>("date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("date");

                    b.Property<int>("no_of_items")
                        .HasColumnType("int")
                        .HasColumnName("no_of_items");

                    b.Property<int>("qty")
                        .HasColumnType("int")
                        .HasColumnName("qty");

                    b.Property<int>("total_qty")
                        .HasColumnType("int")
                        .HasColumnName("total_qty");

                    b.HasKey("Id");

                    b.ToTable("return_details");
                });

            modelBuilder.Entity("E_Invoice_system.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("role_title");

                    b.HasKey("Id");

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleTitle = "Admin"
                        });
                });

            modelBuilder.Entity("E_Invoice_system.Models.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Customers")
                        .HasColumnType("bit")
                        .HasColumnName("customers");

                    b.Property<bool>("Dashboard")
                        .HasColumnType("bit")
                        .HasColumnName("dashboard");

                    b.Property<bool>("Employees")
                        .HasColumnType("bit")
                        .HasColumnName("employees");

                    b.Property<bool>("Inventory")
                        .HasColumnType("bit")
                        .HasColumnName("inventory");

                    b.Property<bool>("Products")
                        .HasColumnType("bit")
                        .HasColumnName("products");

                    b.Property<bool>("Reports")
                        .HasColumnType("bit")
                        .HasColumnName("Reports");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<bool>("Sales")
                        .HasColumnType("bit")
                        .HasColumnName("sales");

                    b.Property<bool>("Settings")
                        .HasColumnType("bit")
                        .HasColumnName("settings");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("roles_permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Customers = true,
                            Dashboard = true,
                            Employees = true,
                            Inventory = true,
                            Products = true,
                            Reports = true,
                            RoleId = 1,
                            Sales = true,
                            Settings = true
                        });
                });

            modelBuilder.Entity("E_Invoice_system.Models.Sale", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("inv_no")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("inv_no")
                        .HasColumnOrder(1);

                    b.Property<string>("date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("date");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<decimal>("discount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("discount");

                    b.Property<string>("expiry_date")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("expiry_date");

                    b.Property<bool>("is_returned")
                        .HasColumnType("bit")
                        .HasColumnName("is_returned");

                    b.Property<int>("no_of_items")
                        .HasColumnType("int")
                        .HasColumnName("no_of_items");

                    b.Property<string>("payment_method")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payment_method");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<int>("qty")
                        .HasColumnType("int")
                        .HasColumnName("qty");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<decimal>("total_price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_price");

                    b.Property<int>("total_qty")
                        .HasColumnType("int")
                        .HasColumnName("total_qty");

                    b.HasKey("id");

                    b.ToTable("sale_details");
                });

            modelBuilder.Entity("E_Invoice_system.Models.StockDetail", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("date_of_expiry")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("date_of_expiry");

                    b.Property<string>("date_of_manafacture")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("date_of_manafacture");

                    b.Property<string>("item_barcode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("item_barcode");

                    b.Property<decimal>("pur_price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("pur_price");

                    b.Property<int>("quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<decimal>("sale_price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("sale_price");

                    b.Property<int>("stock_alert")
                        .HasColumnType("int")
                        .HasColumnName("stock_alert");

                    b.Property<decimal>("total_pur_price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_pur_price");

                    b.Property<decimal>("whole_sale_price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("whole_sale_price");

                    b.HasKey("id");

                    b.ToTable("stock_details");
                });

            modelBuilder.Entity("E_Invoice_system.Models.StoreConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("address");

                    b.Property<string>("Branch")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("branch");

                    b.Property<string>("BusinessNature")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("business_nature");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("city");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comments");

                    b.Property<string>("LogoPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("logo_path");

                    b.Property<string>("OwnerName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("owner_name");

                    b.Property<string>("Phone1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("phone_1");

                    b.Property<string>("Phone2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("phone_2");

                    b.Property<string>("ShopName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("shop_name");

                    b.Property<string>("ShopNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("shop_no");

                    b.HasKey("Id");

                    b.ToTable("store_configurations");
                });

            modelBuilder.Entity("E_Invoice_system.Models.customers", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<string>("cnic")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cnic");

                    b.Property<string>("contact")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contact");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.HasKey("id");

                    b.ToTable("customers");
                });

            modelBuilder.Entity("E_Invoice_system.Models.stock_history", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("date")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("date");

                    b.Property<decimal>("new_purchase_price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("new_purchase_price");

                    b.Property<int>("new_quantity")
                        .HasColumnType("int")
                        .HasColumnName("new_quantity");

                    b.Property<decimal>("new_sale_price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("new_sale_price");

                    b.Property<decimal>("old_purchase_price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("old_purchase_price");

                    b.Property<int>("old_quantity")
                        .HasColumnType("int")
                        .HasColumnName("old_quantity");

                    b.Property<decimal>("old_sale_price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("old_sale_price");

                    b.Property<int>("product_id")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<string>("remarks")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("remarks");

                    b.Property<int?>("user_id")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("id");

                    b.ToTable("stock_history");
                });

            modelBuilder.Entity("E_Invoice_system.Models.users", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<int>("emp_id")
                        .HasColumnType("int")
                        .HasColumnName("emp_id");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password");

                    b.Property<int>("role_id")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<string>("username")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("username");

                    b.HasKey("id");

                    b.HasIndex("emp_id");

                    b.HasIndex("role_id");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            id = 1,
                            email = "admin@pos.com",
                            emp_id = 1,
                            password = "admin123",
                            role_id = 1,
                            status = "Active",
                            username = "admin"
                        });
                });

            modelBuilder.Entity("E_Invoice_system.Models.RolePermission", b =>
                {
                    b.HasOne("E_Invoice_system.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("E_Invoice_system.Models.users", b =>
                {
                    b.HasOne("E_Invoice_system.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("emp_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Invoice_system.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
