// <auto-generated />
using E_Invoice_system.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E_Invoice_system.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260509112904_create_users_table")]
    partial class create_users_table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("E_Invoice_system.Models.Brand", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("brand_title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("brand_title");

                    b.HasKey("id");

                    b.ToTable("brands");
                });

            modelBuilder.Entity("E_Invoice_system.Models.Category", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("category_title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("category_title");

                    b.HasKey("id");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("E_Invoice_system.Models.Currency", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("code")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("code");

                    b.Property<decimal>("exchange_rate")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("exchange_rate");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<string>("symbol")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("symbol");

                    b.HasKey("id");

                    b.ToTable("currencies");
                });

            modelBuilder.Entity("E_Invoice_system.Models.Employee", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<string>("cnic")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cnic");

                    b.Property<string>("date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("date");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("emp_code")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("emp_code");

                    b.Property<string>("full_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("full_name");

                    b.Property<string>("image_path")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_path");

                    b.Property<string>("mobile_no")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mobile_no");

                    b.Property<decimal>("salary")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("salary");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.HasKey("id");

                    b.ToTable("employee");
                });

            modelBuilder.Entity("E_Invoice_system.Models.ProductService", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("barcode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("barcode");

                    b.Property<int?>("brand_id")
                        .HasColumnType("int")
                        .HasColumnName("brand_id");

                    b.Property<int?>("category_id")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<string>("expiry_date")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("expiry_date");

                    b.Property<string>("item_type")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("item_type");

                    b.Property<string>("manufacture_date")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("manufacture_date");

                    b.Property<string>("pic")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("pic");

                    b.Property<string>("prod_name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("prod_name");

                    b.Property<string>("prod_state")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("prod_state");

                    b.Property<string>("remarks")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("remarks");

                    b.Property<int?>("size")
                        .HasColumnType("int")
                        .HasColumnName("size");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<string>("unit")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("unit");

                    b.HasKey("id");

                    b.ToTable("products_services");
                });

            modelBuilder.Entity("E_Invoice_system.Models.ReturnDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Method")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("method");

                    b.Property<int>("SaleId")
                        .HasColumnType("int")
                        .HasColumnName("sale_id");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<string>("billNo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("billNo")
                        .HasColumnOrder(1);

                    b.Property<string>("date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("date");

                    b.Property<int>("no_of_items")
                        .HasColumnType("int")
                        .HasColumnName("no_of_items");

                    b.Property<decimal>("qty")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("qty");

                    b.Property<decimal>("total_qty")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_qty");

                    b.HasKey("Id");

                    b.ToTable("return_details");
                });

            modelBuilder.Entity("E_Invoice_system.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("role_title");

                    b.HasKey("Id");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("E_Invoice_system.Models.Sale", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("billNo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("billNo")
                        .HasColumnOrder(1);

                    b.Property<string>("date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("date");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<decimal>("discount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("discount");

                    b.Property<string>("expiry_date")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("expiry_date");

                    b.Property<bool>("is_returned")
                        .HasColumnType("bit")
                        .HasColumnName("is_returned");

                    b.Property<int>("no_of_items")
                        .HasColumnType("int")
                        .HasColumnName("no_of_items");

                    b.Property<string>("payment_method")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payment_method");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<decimal>("qty")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("qty");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<decimal>("total_price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_price");

                    b.Property<decimal>("total_qty")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_qty");

                    b.HasKey("id");

                    b.ToTable("sale_details");
                });

            modelBuilder.Entity("E_Invoice_system.Models.customers", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<string>("contact")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contact");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.HasKey("id");

                    b.ToTable("customers");
                });

            modelBuilder.Entity("E_Invoice_system.Models.invoices", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("customer_address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("customer_address");

                    b.Property<string>("customer_contact")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("customer_contact");

                    b.Property<string>("customer_name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("customer_name");

                    b.Property<string>("date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("date");

                    b.Property<decimal>("discount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("discount");

                    b.Property<string>("invoice_no")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("invoice_no");

                    b.Property<string>("payment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payment");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<string>("prod_name_service")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("prod_name/service");

                    b.Property<string>("qty_unit_type")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("qty/unit_type");

                    b.Property<string>("seller_address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("seller_address");

                    b.Property<string>("seller_contact")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("seller_contact");

                    b.Property<string>("seller_name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("seller_name");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<decimal>("total_price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_price");

                    b.HasKey("id");

                    b.ToTable("invoices");
                });

            modelBuilder.Entity("E_Invoice_system.Models.users", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<int>("emp_id")
                        .HasColumnType("int")
                        .HasColumnName("emp_id");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password");

                    b.Property<int>("role_id")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<string>("username")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("username");

                    b.HasKey("id");

                    b.HasIndex("emp_id");

                    b.HasIndex("role_id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("E_Invoice_system.Models.users", b =>
                {
                    b.HasOne("E_Invoice_system.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("emp_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Invoice_system.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
