// <auto-generated />
using E_Invoice_system.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E_Invoice_system.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260509101924_create_currencies_table")]
    partial class create_currencies_table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("E_Invoice_system.Models.Currency", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("code")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("code");

                    b.Property<decimal>("exchange_rate")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("exchange_rate");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<string>("symbol")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("symbol");

                    b.HasKey("id");

                    b.ToTable("currencies");
                });
#pragma warning restore 612, 618
        }
    }
}
