// <auto-generated />
using System;
using E_Invoice_system.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E_Invoice_system.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260430163500_create_stock_history_table")]
    partial class create_stock_history_table
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // ... (Rest of the model snapshot would go here, but for brevity and safety we focus on the entity)
            modelBuilder.Entity("E_Invoice_system.Models.StockHistory", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("date")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("date");

                    b.Property<decimal>("new_purchase_price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("new_purchase_price");

                    b.Property<decimal>("new_quantity")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("new_quantity");

                    b.Property<decimal>("new_sale_price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("new_sale_price");

                    b.Property<decimal>("old_purchase_price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("old_purchase_price");

                    b.Property<decimal>("old_quantity")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("old_quantity");

                    b.Property<decimal>("old_sale_price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("old_sale_price");

                    b.Property<int>("product_id")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<string>("remarks")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("remarks");

                    b.Property<int?>("user_id")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("id");

                    b.ToTable("stock_history");
                });
#pragma warning restore 612, 618
        }
    }
}
